### ISSUE TITLE
markdownToTxt is not a function error

### ISSUE THREAD

**Issue by danieladugyan** [Dsek-LTH/web#482]
```bash
3|web  | TypeError: markdownToTxt is not a function
3|web  |     at sendNewArticleNotification (file:///var/www/build/server/chunks/actions2-B0YlyOaI.js:79:52)
3|web  |     at async createArticle (file:///var/www/build/server/chunks/actions2-B0YlyOaI.js:158:5)
3|web  |     at async handle_action_json_request (file:///var/www/build/server/chunks/index-CK8b2p-u.js:871:18)
3|web  |     at async resolve2 (file:///var/www/build/server/chunks/index-CK8b2p-u.js:3425:24)
3|web  |     at async themeHandle (file:///var/www/build/server/chunks/hooks.server-B6vcsvQK.js:513:10)
3|web  |     at async respond (file:///var/www/build/server/chunks/index-CK8b2p-u.js:3317:22)
3|web  |     at async Array.ssr (file:///var/www/build/handler.js:1261:3)
```

**Comment by Isak-Kallini** [comment]
closed by e42a91b
